/*
 * Copyright (C) 2015-present CloudBeat Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

/*
 * Turns a session's command journal into an Oxygen test script.
 *
 * The script this produces has to obey the same rules a hand-written one does: no
 * async/await (Oxygen transforms scripts so they read synchronously), durable locators
 * rather than session refs, and nothing in it that only made sense while exploring.
 */

// Commands that belong to the walkthrough rather than to the test. `snapshot` is how a
// person looks around; `setTimeout` is the interactive wait the CLI sets on every session.
const EXPLORATION_ONLY = ['snapshot', 'setTimeout'];

// Read-only commands are kept only when their value was used. From a journal there is no
// way to know that, so they are emitted as comments rather than dropped - a reader can see
// what was checked and turn it into an assertion.
const INSPECTION_COMMANDS = [
    'getTitle', 'getUrl', 'getText', 'getValue', 'getAttribute', 'getHTML', 'getSource',
    'getCssValue', 'getElementCount', 'getCookies', 'getWindowHandles', 'getWindowSize',
    'getBrowserLogs', 'getXMLPageSource', 'isExist', 'isVisible', 'isSelected',
    'isChecked', 'isInteractable', 'isAlertPresent',
];

export function generateScript(journal, options = {}) {
    const entries = journal.entries || [];
    const refLocators = journal.refLocators || {};
    const includeFailed = !!options.includeFailed;

    const lines = [];
    const warnings = [];
    let emitted = 0;
    // `oxygen session start` always runs web.init(), so a session nobody has touched still
    // has one journal entry. Counting steps that do something is what tells a walkthrough
    // apart from a browser that was merely opened.
    let meaningful = 0;
    let skippedFailed = 0;

    for (const entry of entries) {
        if (EXPLORATION_ONLY.includes(entry.command)) {
            continue;
        }
        if (entry.status === 'failed' && !includeFailed) {
            // a command that failed while exploring recorded a mistake, not a test step
            skippedFailed++;
            continue;
        }

        const rendered = renderArgs(entry, refLocators, warnings);

        // a transaction reads better with a blank line before it, since it opens a section
        if (entry.command === 'transaction' && lines.length) {
            lines.push('');
        }
        for (const warning of rendered.comments) {
            lines.push(`// ${warning}`);
        }

        const call = `${entry.module}.${entry.command}(${rendered.args.join(', ')});`;
        lines.push(INSPECTION_COMMANDS.includes(entry.command) ? `// ${call}  // inspected while exploring` : call);
        emitted++;
        if (entry.command !== 'init') {
            meaningful++;
        }
    }

    return {
        code: renderFile(lines, options),
        emitted,
        meaningful,
        skippedFailed,
        warnings,
    };
}

function renderFile(lines, options) {
    const header = [
        '/*',
        ' * Generated by "oxygen session save" from an interactive walkthrough.',
        ' *',
        ' * Review before committing: locators are taken from the page as it was, and any',
        ' * TODO below marks a step that has no stable locator and will not run as written.',
        ' */',
        '',
    ];
    if (options.name) {
        header.splice(2, 0, ` * Session: ${options.name}`);
    }
    return header.concat(lines).join('\n') + '\n';
}

function renderArgs(entry, refLocators, warnings) {
    const args = [];
    const comments = [];

    for (const arg of entry.args) {
        if (typeof arg === 'string' && arg.startsWith('ref=')) {
            const known = refLocators[arg];
            if (known && known.locator) {
                args.push(quote(known.locator));
                continue;
            }
            // No durable locator exists for this element. Emitting an absolute XPath would
            // produce a script that passes today and breaks on the next markup change,
            // silently. Keeping the ref produces one that fails immediately with a message
            // saying exactly what to do - which is the honest outcome, and visible.
            const described = known ? `${known.role} "${known.name}"` : arg;
            comments.push(`TODO: no stable locator found for ${described} - replace this reference`);
            warnings.push(`${entry.module}.${entry.command}: no stable locator for ${described}`);
            args.push(quote(arg));
            continue;
        }
        args.push(literal(arg));
    }

    return { args, comments };
}

function literal(value) {
    if (typeof value === 'string') {
        return quote(value);
    }
    if (value === null || value === undefined) {
        return String(value);
    }
    return JSON.stringify(value);
}

function quote(value) {
    return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}
