/*
 * Copyright (C) 2015-present CloudBeat Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

/*
 * `oxygen skills install` - put the bundled agent guidance where a coding assistant looks
 * for it, in that assistant's own format.
 *
 * The skills document this CLI's own flags and commands, so their version has to match the
 * CLI's. Shipping them inside the package and installing from there is what keeps the two
 * together: a set copied by hand once goes quietly stale against a newer CLI, and the
 * failure mode is an agent confidently using a flag that no longer exists.
 *
 * Each assistant discovers guidance differently, and none of them read another's format.
 * The skills in skills/ are the single source of truth; everything else here is generated
 * from them at install time, so there is one file to edit when a rule changes:
 *
 *   Claude Code   .claude/skills/<name>/SKILL.md      copied as-is
 *                 .claude/commands/<name>.md          copied as-is
 *   Copilot       .github/instructions/*.instructions.md   skills that declare `applyTo`
 *                 .github/prompts/*.prompt.md              the rest, plus commands
 *                 .github/copilot-instructions.md          always read; a short pointer
 *   Any assistant AGENTS.md                                the cross-tool convention
 *
 * A skill declaring `applyTo` in its frontmatter is guidance that belongs to particular
 * files, so it becomes an always-on instructions file scoped to that glob. A skill without
 * one is task guidance and becomes a prompt the user invokes deliberately - always-on text
 * that applies to everything is text an agent learns to ignore.
 */

import fs from 'fs';
import path from 'path';
import os from 'os';

// Claude Code reads skills from a per-user directory and from a per-project one. The
// project directory is the better default: it can be committed, so a clone brings the
// skills with it and nobody has to remember an install step.
const USER_CLAUDE_DIR = path.join(os.homedir(), '.claude');
const PROJECT_CLAUDE_DIR = '.claude';
const GITHUB_DIR = '.github';
const AGENTS_FILE = 'AGENTS.md';

const KNOWN_AGENTS = ['claude', 'copilot', 'agents'];

// Records which files this command placed, so a later install can remove the ones a
// new version no longer ships. Without it a rename leaves both names installed and the
// stale copy keeps describing flags that have moved on - the exact drift installing
// from the package was meant to prevent.
const MANIFEST = '.oxygen-installed.json';

// Everything written into a file the user also owns goes between these markers, and only
// the text between them is ever replaced. A customer's existing AGENTS.md is theirs.
const BEGIN = '<!-- oxygen:begin - generated by "oxygen skills install"; edits here are overwritten -->';
const END = '<!-- oxygen:end -->';

export default async function skills(argv) {
    const sub = argv._[1];
    if (!sub || sub === 'help') {
        return printUsage();
    }
    if (sub !== 'install' && sub !== 'list' && sub !== 'path') {
        console.error(`Unknown skills command: "${sub}". Expected: install, list, path.`);
        return 1;
    }

    const source = bundledSkillsDir();
    if (!source) {
        console.error(
            'Cannot find the bundled skills. They ship inside the oxygen-cli package;\n' +
            'a source checkout needs "npm run build" first.'
        );
        return 1;
    }
    const available = listSkills(source);
    if (!available.length) {
        console.error(`No skills found in ${source}`);
        return 1;
    }

    if (sub === 'path') {
        console.log(source);
        return 0;
    }
    if (sub === 'list') {
        return printList(source, available);
    }

    const agents = parseAgents(argv.agent);
    if (!agents) {
        console.error(`Unknown --agent value. Expected one or more of: ${KNOWN_AGENTS.join(', ')}, all.`);
        return 1;
    }
    if (argv.user && !agents.includes('claude')) {
        console.error('--user applies to the Claude Code install only; drop it or add --agent=claude.');
        return 1;
    }

    const projectDir = path.resolve(argv.cwd || process.cwd());
    const commandsSource = bundledCommandsDir();
    const written = [];
    const removed = [];

    for (const agent of agents) {
        let result;
        if (agent === 'claude') {
            result = installForClaude({ source, available, commandsSource, projectDir, argv });
        }
        else if (agent === 'copilot') {
            result = installForCopilot({ source, available, commandsSource, projectDir });
        }
        else {
            result = installAgentsFile({ source, available, projectDir });
        }
        if (result.error) {
            console.error(result.error);
            return 1;
        }
        written.push(...result.written);
        removed.push(...(result.removed || []));
    }

    console.log(`Installed Oxygen agent guidance for: ${agents.join(', ')}\n`);
    for (const file of written) {
        console.log(`  ${path.relative(projectDir, file) || file}`);
    }
    if (removed.length) {
        console.log(`\nRemoved ${removed.length} file(s) this version no longer ships:`);
        for (const file of removed) {
            console.log(`  ${path.relative(projectDir, file) || file}`);
        }
    }
    printNextSteps(agents, argv);
    return 0;
}

/*
 * Claude Code: the skills and commands are already in its format, so they are copied
 * verbatim. Only ever prune what a previous run put here, never a skill the user wrote
 * that happens to share our naming.
 */
function installForClaude({ source, available, commandsSource, projectDir, argv }) {
    const root = argv.user ? USER_CLAUDE_DIR : path.join(projectDir, PROJECT_CLAUDE_DIR);
    const skillsDir = path.join(root, 'skills');

    const ours = previouslyInstalled(skillsDir);
    const clashes = available.filter(
        (name) => fs.existsSync(path.join(skillsDir, name)) && !ours.includes(name)
    );
    if (clashes.length && !argv.force) {
        return {
            error: `These skills are already installed in ${skillsDir}:\n` +
                clashes.map((name) => `  ${name}`).join('\n') +
                '\n\nPass --force to replace them with this version.',
        };
    }

    fs.mkdirSync(skillsDir, { recursive: true });
    const removed = [];
    for (const name of ours.filter((name) => !available.includes(name))) {
        fs.rmSync(path.join(skillsDir, name), { recursive: true, force: true });
        removed.push(path.join(skillsDir, name));
    }
    const written = [];
    for (const name of available) {
        const to = path.join(skillsDir, name);
        fs.rmSync(to, { recursive: true, force: true });
        fs.cpSync(path.join(source, name), to, { recursive: true });
        written.push(to);
    }
    writeManifest(skillsDir, { skills: available });

    // Commands are Claude Code slash commands. Namespaced, because /run and /triage are
    // names a project may well want for itself.
    if (commandsSource) {
        const commandsDir = path.join(root, 'commands');
        const files = listCommands(commandsSource).map((name) => ({
            name: `oxygen-${name}.md`,
            content: fs.readFileSync(path.join(commandsSource, `${name}.md`), 'utf8'),
        }));
        const result = syncGeneratedFiles(commandsDir, files);
        written.push(...result.written);
        removed.push(...result.removed);
    }
    return { written, removed };
}

/*
 * Copilot: same content, its own formats. Instructions files are read automatically for
 * files matching their `applyTo` glob; prompt files are invoked as /name in chat.
 */
function installForCopilot({ source, available, commandsSource, projectDir }) {
    const githubDir = path.join(projectDir, GITHUB_DIR);
    const written = [];
    const removed = [];

    const instructions = [];
    const prompts = [];
    for (const name of available) {
        const skill = readDoc(path.join(source, name, 'SKILL.md'));
        if (skill.frontmatter.applyTo) {
            instructions.push({
                name: `${name}.instructions.md`,
                content: renderInstructions(skill),
            });
        }
        else {
            prompts.push({ name: `${name}.prompt.md`, content: renderPrompt(skill) });
        }
    }
    if (commandsSource) {
        for (const name of listCommands(commandsSource)) {
            // A command that only says "load skill X" would duplicate the prompt already
            // generated from that skill, and two prompts with the same advice is one more
            // than anybody needs.
            if (available.includes(`oxygen-${name}`)) {
                continue;
            }
            const doc = readDoc(path.join(commandsSource, `${name}.md`));
            prompts.push({ name: `oxygen-${name}.prompt.md`, content: renderPrompt(doc) });
        }
    }

    for (const [dir, files] of [['instructions', instructions], ['prompts', prompts]]) {
        const result = syncGeneratedFiles(path.join(githubDir, dir), files);
        written.push(...result.written);
        removed.push(...result.removed);
    }

    const pointer = path.join(githubDir, 'copilot-instructions.md');
    if (upsertBlock(pointer, renderCopilotPointer(instructions, prompts))) {
        written.push(pointer);
    }
    return { written, removed };
}

/*
 * AGENTS.md is the one file every assistant has converged on. A customer may already have
 * one, so this only ever owns the text between the markers.
 */
function installAgentsFile({ source, available, projectDir }) {
    const file = path.join(projectDir, AGENTS_FILE);
    const summaries = available.map((name) => ({
        name,
        description: readDoc(path.join(source, name, 'SKILL.md')).frontmatter.description || '',
    }));
    upsertBlock(file, renderAgentsBlock(summaries));
    return { written: [file] };
}

/* ---------- rendering ---------- */

function renderInstructions(doc) {
    return [
        '---',
        `applyTo: "${doc.frontmatter.applyTo}"`,
        '---',
        generatedNote(doc.name),
        '',
        doc.body,
    ].join('\n');
}

function renderPrompt(doc) {
    const description = (doc.frontmatter.description || '').replace(/^["']|["']$/g, '');
    return [
        '---',
        'mode: agent',
        `description: ${JSON.stringify(description)}`,
        '---',
        generatedNote(doc.name),
        '',
        doc.body,
    ].join('\n');
}

function renderCopilotPointer(instructions, prompts) {
    const lines = [
        '## Oxygen test automation',
        '',
        'This project runs [Oxygen](https://github.com/oxygenhq/oxygen) tests. Oxygen test',
        'scripts are **not** ordinary Node.js and not WebdriverIO or Playwright - they are',
        'transformed before they run, so do not write `async`/`await` in them.',
        '',
        'Detailed guidance is installed alongside this file:',
        '',
    ];
    for (const file of instructions) {
        lines.push(`- \`.github/instructions/${file.name}\` - applied automatically to the files it covers.`);
    }
    for (const file of prompts) {
        lines.push(`- \`/${file.name.replace(/\.prompt\.md$/, '')}\` - prompt, invoke it in chat.`);
    }
    lines.push(
        '',
        'Running tests: pass `--headless` for anything unattended, and `--rf=agent` when the',
        'output will be read rather than watched - it writes `agent-report.json` with the',
        'failing step, its script line and a page snapshot.',
        '',
        'If a run using `--autowd` fails with `EPERM` or `EACCES` naming a driver cache path,',
        'that is a permission problem, not a test or driver problem: pass',
        '`--wdcache=<writable path>` rather than editing the test or dropping `--autowd`.'
    );
    return lines.join('\n');
}

function renderAgentsBlock(summaries) {
    const lines = [
        '## Oxygen test automation',
        '',
        'Oxygen test scripts are transformed before they run: **do not write `async`/`await`**',
        'in them. Run unattended tests with `--headless`, and add `--rf=agent` when the output',
        'will be read rather than watched.',
        '',
        'If `--autowd` fails with `EPERM`/`EACCES` naming a driver cache path, that is a',
        'permission problem - pass `--wdcache=<writable path>`, do not edit the test.',
        '',
        'Task guidance shipped with this version of oxygen-cli:',
        '',
    ];
    for (const skill of summaries) {
        lines.push(`- **${skill.name}** - ${firstSentence(skill.description)}`);
    }
    lines.push(
        '',
        'Reinstall after upgrading oxygen-cli, so the guidance matches the CLI:',
        '`oxygen skills install`.'
    );
    return lines.join('\n');
}

function generatedNote(name) {
    return `<!-- Generated by "oxygen skills install" from ${name} (oxygen-cli ${packageVersion() || 'unknown'}). ` +
        'Edit the skill and reinstall; changes here are overwritten. -->';
}

/* ---------- file helpers ---------- */

/*
 * Writes `files` into `dir` and removes only what a previous run of this command left
 * there. Files the user wrote alongside ours are never touched.
 */
function syncGeneratedFiles(dir, files) {
    const written = [];
    const removed = [];
    const previous = previouslyInstalled(dir, 'files');
    const names = files.map((file) => file.name);

    if (!files.length && !previous.length) {
        return { written, removed };
    }
    fs.mkdirSync(dir, { recursive: true });
    for (const name of previous.filter((name) => !names.includes(name))) {
        const stale = path.join(dir, name);
        if (fs.existsSync(stale)) {
            fs.rmSync(stale, { force: true });
            removed.push(stale);
        }
    }
    for (const file of files) {
        const to = path.join(dir, file.name);
        fs.writeFileSync(to, file.content.endsWith('\n') ? file.content : `${file.content}\n`);
        written.push(to);
    }
    writeManifest(dir, { files: names });
    return { written, removed };
}

/*
 * Replaces the marked block in an existing file, or creates the file. Returns whether
 * anything was written. Content outside the markers is left exactly as it was - these
 * files belong to the project, not to this command.
 */
function upsertBlock(file, block) {
    const wrapped = `${BEGIN}\n\n${block}\n\n${END}`;
    let existing = '';
    try {
        existing = fs.readFileSync(file, 'utf8');
    }
    catch (e) {
        // not there yet: created below
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!existing.trim()) {
        fs.writeFileSync(file, `${wrapped}\n`);
        return true;
    }
    const start = existing.indexOf(BEGIN);
    const end = existing.indexOf(END);
    if (start !== -1 && end > start) {
        const updated = existing.slice(0, start) + wrapped + existing.slice(end + END.length);
        fs.writeFileSync(file, updated);
        return true;
    }
    // Existing file we have never touched: append rather than rewrite, and preserve the
    // line endings it already uses.
    const eol = existing.includes('\r\n') ? '\r\n' : '\n';
    const separator = existing.endsWith('\n') ? '' : eol;
    fs.writeFileSync(file, existing + separator + eol + wrapped.split('\n').join(eol) + eol);
    return true;
}

function writeManifest(dir, extra) {
    fs.writeFileSync(
        path.join(dir, MANIFEST),
        JSON.stringify({ version: packageVersion(), ...extra }, null, 2) + '\n'
    );
}

function previouslyInstalled(target, key = 'skills') {
    try {
        const parsed = JSON.parse(fs.readFileSync(path.join(target, MANIFEST), 'utf8'));
        return Array.isArray(parsed[key]) ? parsed[key] : [];
    }
    catch (e) {
        // no manifest, or an unreadable one: treat everything present as not ours
        return [];
    }
}

/*
 * Splits `---` frontmatter from the body. A line scan rather than a YAML parser: these are
 * a few known scalar fields, and a dependency to read them would not earn its place.
 */
function readDoc(file) {
    const text = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
    const match = /^---\n([\s\S]*?)\n---\n?/.exec(text);
    const frontmatter = {};
    if (match) {
        for (const line of match[1].split('\n')) {
            const field = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
            if (field) {
                frontmatter[field[1]] = field[2].trim().replace(/^["']|["']$/g, '');
            }
        }
    }
    return {
        // The skill's own name where it declares one, so the generated note points at the
        // file to edit rather than at "SKILL.md", of which there are several.
        name: frontmatter.name || path.basename(file, '.md'),
        frontmatter,
        body: match ? text.slice(match[0].length).trim() : text.trim(),
    };
}

/* ---------- discovery ---------- */

/*
 * Where the bundled assets sit at run time. Built output lives in build/, one level below
 * the package root, and the source tree is laid out the same way relative to src/ - so the
 * same two candidates cover an installed package and a working checkout.
 */
function bundledDir(name) {
    const candidates = [
        path.resolve(__dirname, '..', '..', name),
        path.resolve(__dirname, '..', '..', '..', name),
    ];
    return candidates.find((dir) => fs.existsSync(dir)) || null;
}

export function bundledSkillsDir() {
    return bundledDir('skills');
}

export function bundledCommandsDir() {
    return bundledDir('commands');
}

function listSkills(dir) {
    try {
        return fs.readdirSync(dir, { withFileTypes: true })
            .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(dir, entry.name, 'SKILL.md')))
            .map((entry) => entry.name)
            .sort();
    }
    catch (e) {
        return [];
    }
}

function listCommands(dir) {
    try {
        return fs.readdirSync(dir)
            .filter((name) => name.endsWith('.md'))
            .map((name) => name.replace(/\.md$/, ''))
            .sort();
    }
    catch (e) {
        return [];
    }
}

function parseAgents(value) {
    if (value === undefined || value === true || value === 'all') {
        return [...KNOWN_AGENTS];
    }
    const requested = String(value).split(',').map((name) => name.trim().toLowerCase()).filter(Boolean);
    if (!requested.length || requested.some((name) => !KNOWN_AGENTS.includes(name))) {
        return null;
    }
    return KNOWN_AGENTS.filter((name) => requested.includes(name));
}

function packageVersion() {
    try {
        return require('../../../package.json').version;
    }
    catch (e) {
        return null;
    }
}

function firstSentence(text) {
    const sentence = String(text).split(/(?<=[.!?])\s/)[0].trim();
    return sentence.length > 88 ? sentence.slice(0, 87) + '…' : sentence;
}

function printList(source, available) {
    console.log(`${available.length} skills bundled with oxygen-cli:\n`);
    for (const name of available) {
        const doc = readDoc(path.join(source, name, 'SKILL.md'));
        const scope = doc.frontmatter.applyTo ? `applies to ${doc.frontmatter.applyTo}` : 'invoked on demand';
        console.log(`   ${name.padEnd(16)} ${firstSentence(doc.frontmatter.description || '')}`);
        console.log(`   ${''.padEnd(16)} ${scope}`);
    }
    const commandsSource = bundledCommandsDir();
    if (commandsSource) {
        const commands = listCommands(commandsSource);
        console.log(`\n${commands.length} commands: ${commands.join(', ')}`);
    }
    console.log('\nInstall them with: oxygen skills install');
    return 0;
}

function printNextSteps(agents, argv) {
    if (agents.includes('claude')) {
        console.log(
            argv.user
                ? '\nClaude Code: available in every project on this machine.'
                : '\nClaude Code: picks them up on its next start; "/skills" lists what it can see.'
        );
    }
    if (agents.includes('copilot')) {
        console.log(
            'Copilot: instructions apply automatically to matching files; prompts are invoked\n' +
            '  as /<name> in chat. VS Code needs "chat.promptFiles" enabled to see prompt files.'
        );
    }
    if (!argv.user) {
        console.log('\nCommit these files so anyone who clones the project gets them too.');
    }
}

function printUsage() {
    console.log(`Usage: oxygen skills <command>

  install        Install the bundled agent guidance into this project, in each
                 assistant's own format.
                 --agent=<list>  claude, copilot, agents (AGENTS.md), or all.
                                 Defaults to all.
                 --user          install the Claude Code skills into ~/.claude
                                 instead, for every project on this machine
                 --force         replace skills that are already installed
  list           Show which skills ship with this version of Oxygen.
  path           Print the directory the bundled skills are read from.

The skills teach an agent how to structure an Oxygen project, write tests, drive a
session, and read a failure report. They document this CLI's flags, so install them
from the same version of Oxygen you are running, and reinstall after an upgrade.`);
    return 0;
}
