import Assert from './module-assert';
import Date from './module-date';
import DB from './module-db';
import Email from './module-email';
import Eyes from './module-eyes';
import Http from './module-http';
import Log from './module-log';
import Mailinator from './module-mailinator';
import Mob from './module-mob';
import Pdf from './module-pdf';
import Serial from './module-serial';
import Shell from './module-shell';
import Soap from './module-soap';
import Twilio from './module-twilio';
import Web from './module-web';
import Win from './module-win';

export const assert = Assert;
export const date = Date;
export const db = DB;
export const email = Email;
export const eyes = Eyes;
export const http = Http;
export const log = Log;
export const mailinator = Mailinator;
export const mob = Mob;
export const pdf = Pdf;
export const serial = Serial;
export const shell = Shell;
export const soap = Soap;
export const twilio = Twilio;
export const web = Web;
export const win = Win;